theme: jekyll-theme-minimal

title: "Archit Yadav"

markdown: kramdown

sidetext: |
    <p>Master's student at Université Grenoble Alpes</p>
    <p> M1 MoSIG (ENSIMAG & IM2AG)</p> 

extralinks: |

    <li><a href="mailto:archityadav97@gmail.com"><img src="images/gmail_200px.png"></a></li>
    <li><a href="mailto:archit.yadav@etu.univ-grenoble-alpes.fr"><img src="images/uga_146px.png"></a></li>
    
    <li><a href="https://github.com/archity/"><img src="images/GitHub-Mark-64px.png"></a></li>
    <li><a href="https://www.linkedin.com/in/archit-yadav-95482b156/"><img src="images/Linkedin-64px.png"></a></li>

