#theme: jekyll-theme-midnight

plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md


theme: jekyll-theme-minimal
title: Archit Yadav
description: My super cool description
logo: https://github.com/archity/archity.github.io/blob/master/images/archit-hike.jpeg?raw=true
